dist: trusty
sudo: required
language: go
services:
  - docker
go:
  - 1.12.x
env:
  - GOMAXPROCS=4 GO111MODULE=on
install:
  - go get golang.org/x/crypto/pkcs12
  - go get github.com/pkg/errors
  - go get github.com/hashicorp/terraform@v0.12.19
  - go mod tidy
  - go mod vendor
script:
  - make dist
before_deploy:
  - export TRAVIS_TAG="v3.0.5"
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  draft: true
  overwrite: false
  api_key:
    secure: j/9wFrAy2aNDi+k+H9zoXb6uZ5ZlYi3MLWJzq/bXMAOeEUn6K+VA+ymnH6V7PNtp0m3RcpVNyO/I22z+b+06xrP4diqUd3ocQ3rCYZlMhs9afg88SFeK/nv7edghBgk8WBYL8pk19Qx65wwVW/MQtlZzWndVXgRZjGygN2ekyEANQZqSYU8MyBE4poOrcStilEhawBPBSE52FKpQc8DCu14TrsiZrKEiZYcx18caIyOUm7UN1hjJtJ7k0z8hKskPE+0debH/tqmixs/LOefmc8V+nJdi9y5q+oA0czPw9KSGonaOLSMiWGM7hAZVW/3N5g2k/u5GRZKSxfYWnS0DHzE6dzjMoRwusEqcYkqxdYQl+ibx+f53oB3vgAQwBC62ixt0UPlDqNR3yd2Qo+DNE2s+6cobz3csu9YpkKxr/5x463H2+cSlzFw/KtiNZAYgQPLrauaGQgG4xOxRPXDBIGDsz3LAeQKw0BgSx40cYTohpvxVrY4cNSFmMYirEcUHqzCvPTvL1I15Dk7LnxcW03gY9aAIAQRx6XaOayeHyJM8Xfx0C1qTjor1k8vtTd+mHdabq0WFothtOCf4UzXUkNx4shWOfO2WugDsB7bqLNam0j2w+ZIHuvXGUnM3MMgh0Zzg5hMbemziTQR8ewaepk0lDyNq5oyPJZP0vhgcX9E=
  file_glob: true
  file: _bin/terraform-provider-ddcloud.*.zip
  on:
    repo: hhakkaev/dd-cloud-compute-terraform
    branch: development\/v3.0
  skip_cleanup: 'true'
